### ISSUE TITLE
Error displayed in console when there is no cache

### ISSUE THREAD

**Issue by ptrkvsky** [shaunchander/astro-pwa-starter#1]
Hi,
There is somme errors displayed in the console when there is no cache.
Do you know how to solve that ? 

![Screenshot from 2022-09-03 10-42-39](https://user-images.githubusercontent.com/33042640/188263195-1d367597-718f-4e05-bd22-6be75f406a3f.png)
![Screenshot from 2022-09-03 10-41-55](https://user-images.githubusercontent.com/33042640/188263198-66ceda93-49a4-4fde-a745-6f3239a6230c.png)

**Comment by shaunchander** [comment]
@ptrkvsky  🙏 thanks so much for submitting a PR for this issue, with your work, we can now build Astro sites that score perfect 100s across the board AND have full PWA optimization 🎉
