### ISSUE TITLE
Opens in webview on iOS

### ISSUE THREAD

**Issue by zainul1996** [shaunchander/astro-pwa-starter#3]
Installation works on all platform but on iOS, when added to homepage, it opens a webview with address bar. Tried debugging but not too sure what was the issue

**Comment by zainul1996** [comment]
Steps taken:
1. Cloned project, installed dependancies
2. Pushed to vercel for hosting 
3. Opened the url on iPhone and added to homescreen

**Comment by shaunchander** [comment]
Hey @zainul1996, can you post a screenshot of what you see when you open the website up on iOS after you downloaded it as a PWA?

**Comment by zainul1996** [comment]
@shaunchander this is what I see right after opening the app
![IMG_4231](https://user-images.githubusercontent.com/14123713/195234671-58e9f652-6e36-4101-82c6-ba6596146e31.PNG)

**Comment by shaunchander** [comment]
@zainul1996 this looks like the correct behavior to me? 

If you're trying to hide the browser's navigation completely try setting this line (https://github.com/shaunchander/astro-pwa-starter/blob/master/utils/seoConfig.ts#L34) to `fullscreen`.

**Comment by zainul1996** [comment]
@shaunchander yes! that was it! thank you for the quick response
